networks:
    web:
        driver: bridge

volumes:
    mariadb:
        driver: local

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - '${APP_PORT:-80}:80'
        links:
            - php:php
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
            - ./docker/logs/nginx:/var/logs/nginx:rw
        depends_on:
            - php
            - db
        networks:
            - web
        restart: always
        tty: true

    db:
        image: 'mariadb:10'
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'mariadb:/var/lib/mysql'
        networks:
            - web
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
        restart: unless-stopped
        tty: true
    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins_server
        user: root
        ports:
        - "8081:8080"
        volumes:
        - ./jenkins:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        networks:
        - web
    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - '${FORWARD_PHP_PORT:-9000}:9000'
        networks:
            - web
        depends_on:
            - db
        restart: unless-stopped
        tty: true
        links:
            - db:db
    node:
        build:
            context: ./docker/node
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
            - /var/www/html/node_modules
        ports:
            - '5173:5173'
        networks:
            - web
        restart: unless-stopped
        tty: true
        depends_on:
            - php



